language: node_js
node_js: 8
cache:
  directories:
    - node_modules

# the following is required for favicon-emoji to run on linux
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348227535
sudo: required
addons:
  chrome: stable
