language: node_js
node_js: 10
cache: npm
before_deploy:
  - cd examples/mdx-deck
  - npm install
  - npm run build
deploy:
  provider: surge
  project: examples/mdx-deck/dist
  domain: emoji-favicon-mdx-deck.surge.sh
  skip_cleanup: true
  on:
    branch: master